[package]
name = "testwhp"
version = "0.1.0"
authors = ["Alessandro Pilotti <apilotti@cloudbasesolutions.com>"]

[dependencies]
libwhp = { path = "../libwhp" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["memoryapi"] }